apiVersion: v1
kind: Pod
metadata:
  name: busybox-2
  labels:
    app: busybox-2
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-2
  restartPolicy: Always