apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
  labels:
    app: busybox-1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-1
  restartPolicy: Always